hydra:
  run:
    dir: .
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stderr
    root:
      level: INFO
      handlers: [console]
    loggers:
      hydra:
        level: INFO
        handlers: [console]
        propagate: false

chase:
  hypers:
    num_samples: 5
    num_burnin: 100
    num_thin: 10
  posterior:
    num_samples: 10
  elliptical:
    num_samples: 11
    num_burnin: 1
    num_thin: 1
  
gp:
  kernel: Matern52
  lengthscale_prior: [0.01, 1.0]
  amplitude_prior: [0.01, 10.0]
  jitter: 1e-4
  noise_missing: 1e4
  num_rff: 501

mockup:
  seed: 13
  num_species: 2
  num_atoms: 100
  noise: 0.0
  num_phases: 2

